### ISSUE TITLE
Cancelled workflows are marked as failed

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#223]
### Problem description

In the previous version cancelled workflows were marked as cancelled. In v0.6.0 they are marked as failed.

**Comment by jamesjmurtagh** [comment]
I believe this is because the backend now returns `failed` if the instance was cancelled. The instance logs also suggest that the cancellation is interpreted as an error:

![image](https://user-images.githubusercontent.com/23179125/150702448-046f59eb-955b-42c8-b010-eb55897555a2.png)

![image](https://user-images.githubusercontent.com/23179125/150702432-40b4718b-f296-43a4-a214-ced6adf2cae7.png)

The UI is already written to use a grey 'Cancelled' tag (instead of a red 'Failed' tag) if the instance `status` field is `cancelled` - so remedying this in the back end will automatically 'fix' the issue on the UI.

Alternatively, if this is the behaviour we want/expect from the back end, I could modify the UI logic so that if the instance has `errorCode: "direktiv.cancels.api"` it will also display as Cancelled.

**Comment by jensg-st** [comment]
Wondering why we changed that. But if we can "fix" it by using "direktiv.cancels.api" that would be nice
